"""restore deleted db

Revision ID: 50cd7d47bb13
Revises: 7bfcaf9b4a1b
Create Date: 2025-10-29 23:21:53.835065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cd7d47bb13'
down_revision = '7bfcaf9b4a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orase'))
    )
    with op.batch_alter_table('orase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orase_nume'), ['nume'], unique=True)

    op.create_table('producatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producatori'))
    )
    with op.batch_alter_table('producatori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producatori_nume'), ['nume'], unique=True)

    op.create_table('stari_comanda_la_producator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stari_comanda_la_producator'))
    )
    with op.batch_alter_table('stari_comanda_la_producator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stari_comanda_la_producator_nume'), ['nume'], unique=True)

    op.create_table('comenzi_la_producator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datatimp', sa.DateTime(), nullable=False),
    sa.Column('id_producator', sa.Integer(), nullable=False),
    sa.Column('id_stare', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producator'], ['producatori.id'], name=op.f('fk_comenzi_la_producator_id_producator_producatori')),
    sa.ForeignKeyConstraint(['id_stare'], ['stari_comanda_la_producator.id'], name=op.f('fk_comenzi_la_producator_id_stare_stari_comanda_la_producator')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comenzi_la_producator'))
    )
    with op.batch_alter_table('comenzi_la_producator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comenzi_la_producator_datatimp'), ['datatimp'], unique=False)

    op.create_table('produse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=40), nullable=False),
    sa.Column('id_producator', sa.Integer(), nullable=False),
    sa.Column('cantitate_stoc', sa.Integer(), nullable=True),
    sa.Column('pret_unitar', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producator'], ['producatori.id'], name=op.f('fk_produse_id_producator_producatori')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produse'))
    )
    with op.batch_alter_table('produse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produse_id_producator'), ['id_producator'], unique=False)

    op.create_table('produse_comenzi_la_producator',
    sa.Column('id_produs', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('pret_unitar', sa.Float(), nullable=False),
    sa.Column('cantitate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comanda'], ['comenzi_la_producator.id'], name=op.f('fk_produse_comenzi_la_producator_id_comanda_comenzi_la_producator')),
    sa.ForeignKeyConstraint(['id_produs'], ['produse.id'], name=op.f('fk_produse_comenzi_la_producator_id_produs_produse')),
    sa.PrimaryKeyConstraint('id_produs', 'id_comanda', name=op.f('pk_produse_comenzi_la_producator'))
    )
    op.create_table('produse_orase',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('oras_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oras_id'], ['orase.id'], name=op.f('fk_produse_orase_oras_id_orase')),
    sa.ForeignKeyConstraint(['product_id'], ['produse.id'], name=op.f('fk_produse_orase_product_id_produse')),
    sa.PrimaryKeyConstraint('product_id', 'oras_id', name=op.f('pk_produse_orase'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produse_orase')
    op.drop_table('produse_comenzi_la_producator')
    with op.batch_alter_table('produse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produse_id_producator'))

    op.drop_table('produse')
    with op.batch_alter_table('comenzi_la_producator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comenzi_la_producator_datatimp'))

    op.drop_table('comenzi_la_producator')
    with op.batch_alter_table('stari_comanda_la_producator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stari_comanda_la_producator_nume'))

    op.drop_table('stari_comanda_la_producator')
    with op.batch_alter_table('producatori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producatori_nume'))

    op.drop_table('producatori')
    with op.batch_alter_table('orase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orase_nume'))

    op.drop_table('orase')
    # ### end Alembic commands ###
