"""unic rol si nume_utilizator

Revision ID: 52702b1b0866
Revises: da888c7ff3b4
Create Date: 2025-11-10 10:32:11.801929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52702b1b0866'
down_revision = 'da888c7ff3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roluri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roluri_nume'), ['nume'], unique=True)

    with op.batch_alter_table('utilizatori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilizatori_nume_utilizator'), ['nume_utilizator'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilizatori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilizatori_nume_utilizator'))

    with op.batch_alter_table('roluri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roluri_nume'))

    # ### end Alembic commands ###
