"""empty message

Revision ID: 7ced5028a781
Revises: ae107b6911ab
Create Date: 2025-11-27 12:53:59.974720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ced5028a781'
down_revision = 'ae107b6911ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roluri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('permisiuni', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_roluri_default'), ['default'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roluri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roluri_default'))
        batch_op.drop_column('permisiuni')
        batch_op.drop_column('default')

    # ### end Alembic commands ###
