"""adaugare confirmare utilizator

Revision ID: ae107b6911ab
Revises: 52702b1b0866
Create Date: 2025-11-17 22:38:27.107325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae107b6911ab'
down_revision = '52702b1b0866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilizatori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmat', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilizatori', schema=None) as batch_op:
        batch_op.drop_column('confirmat')

    # ### end Alembic commands ###
