"""utilizator-rol-comanda-client

Revision ID: da888c7ff3b4
Revises: 50cd7d47bb13
Create Date: 2025-11-08 23:16:27.775788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da888c7ff3b4'
down_revision = '50cd7d47bb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roluri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roluri'))
    )
    op.create_table('stari_comanda_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stari_comanda_client'))
    )
    with op.batch_alter_table('stari_comanda_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stari_comanda_client_nume'), ['nume'], unique=True)

    op.create_table('utilizatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume_utilizator', sa.String(length=30), nullable=False),
    sa.Column('prenume', sa.String(), nullable=False),
    sa.Column('nume_familie', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roluri.id'], name=op.f('fk_utilizatori_id_rol_roluri')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilizatori'))
    )
    op.create_table('comenzi_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datatimp', sa.DateTime(), nullable=False),
    sa.Column('id_utilizator', sa.Integer(), nullable=False),
    sa.Column('id_stare', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_stare'], ['stari_comanda_client.id'], name=op.f('fk_comenzi_client_id_stare_stari_comanda_client')),
    sa.ForeignKeyConstraint(['id_utilizator'], ['utilizatori.id'], name=op.f('fk_comenzi_client_id_utilizator_utilizatori')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comenzi_client'))
    )
    with op.batch_alter_table('comenzi_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comenzi_client_datatimp'), ['datatimp'], unique=False)

    op.create_table('produse_comenzi_client',
    sa.Column('id_produs', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('pret_unitar', sa.Float(), nullable=False),
    sa.Column('cantitate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comanda'], ['comenzi_client.id'], name=op.f('fk_produse_comenzi_client_id_comanda_comenzi_client')),
    sa.ForeignKeyConstraint(['id_produs'], ['produse.id'], name=op.f('fk_produse_comenzi_client_id_produs_produse')),
    sa.PrimaryKeyConstraint('id_produs', 'id_comanda', name=op.f('pk_produse_comenzi_client'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produse_comenzi_client')
    with op.batch_alter_table('comenzi_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comenzi_client_datatimp'))

    op.drop_table('comenzi_client')
    op.drop_table('utilizatori')
    with op.batch_alter_table('stari_comanda_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stari_comanda_client_nume'))

    op.drop_table('stari_comanda_client')
    op.drop_table('roluri')
    # ### end Alembic commands ###
