from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, SelectField, HiddenField, IntegerField
from wtforms.validators import DataRequired, InputRequired, Length, Email, Regexp, EqualTo, NumberRange
from wtforms import ValidationError

#from flask_pagedown.fields import PageDownField

class ProducerAddForm(FlaskForm):
    #Post de timp text simplu
    name = StringField("Producator:", validators=[DataRequired()])
    #body = PageDownField("What's on your mind?", validators = [DataRequired()])
    action = HiddenField(default="add") #<input type="hidden", name="action", value="adauga_producator">

    submit = SubmitField("Adauga", name="submit_add_producer_form",) 
    # '"Adauga" - the value; name - the key , name="submit_add_producer_form"
    # if no name provided, the name will be exactly the name of the variable - in this case - submit
    
    cancel = SubmitField("Renunta")

    # HOW the request generated by this form looks like:
    #request.form: ImmutableMultiDict([
    # ('csrf_token', 'IjZmYmRkYjAwNTJjYjIzOTRlZjZiMTI4NzcwYjI5MWZlMmRkZTMxMjEi.aH3jtQ.ECqWOWwNVY1ad5l4DRPRoAei6ZM'), 
    # ('producer_name', 'test'),                  # the variable name as no 'name' argument
    # ('submit_add_producer_form', 'Adauga')])    # name argument provided - will be used as key instead of submit var name

class ProductModifyForm(FlaskForm):
    name = StringField("Nume produs", validators=[DataRequired(message="Este necesar sa introduceti numele produsului!")])
    producer_id = SelectField("Producator", choices=[])
    #cantitate_stoc = StringField("Cantitate Stoc", validators=[NumberRange(message="Introduceti o valoare numerica pentru cantitate stoc!")])
    #cantitate_stoc = StringField("Cantitate Stoc", validators=[DataRequired(message="Introduceti un numar intreg pentru cantitate stoc!")])
    cantitate_stoc = IntegerField("Cantitate Stoc", validators=[DataRequired(message="Introduceti un numar intreg pentru cantitate stoc!")])
    # IntegerField ramane cu valoarea completata in formular dupa un submit care nu face nimic
    # Atat numele (StringField) cat si producer_id (SelectField) se seteaza la valorile citite pentru produs 
    # - vezi view-ul modifica_produs
    # IntegerField - pare sa aiba un bug.
    # Pastrez totusi IntegerField, se face validare si in Browser - cu HTML5 - faptul ca este completat si este numar
    # Cel mai probabil, in varianta cu functionalitatea de modificare implementata - modific produsul si redirectionez catre produse
    # nu o sa apara problema care se vede cand nu exista aceasta functionalitate si la submit, se reincarca formularul din nou
    submit = SubmitField("Modifica")
    cancel = SubmitField("Renunta")