"""Adaugat coloana pret la produse

Revision ID: b68869be973e
Revises: 
Create Date: 2022-08-12 13:57:35.741073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68869be973e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produse', sa.Column('pret', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produse', 'pret')
    # ### end Alembic commands ###
